#!/bin/bash
## To enable this check, run
## git config core.hooksPath .githooks

VFILE=config.yml

if git diff --cached --exit-code --name-only $VFILE; then
    exit 0;
fi

if [[ $(head -n 1 $VFILE) == *ANSIBLE_VAULT* ]]; then
    exit 0;
else
    echo "Error: Attempt to commit with unencrypted vault.yml"
    exit 1;
fi
