services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - POSTGRES_USER={{ postgres.username }}
            - POSTGRES_PASSWORD={{ postgres.userpass }}
        expose:
            - 5432
        volumes:
            # Backup path
            -  /data/postgres:/data                 # backup here

            # Storage paths
            - ./pg_data:/var/lib/postgresql/data    # PGDATA

            # Log files path
            - ./logs:/logs

            # Configuration files
            - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            - ./configs/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

            # Helper scripts
            - ./configs/postgr.sh:/postgr.sh


networks:
    default:
        external: true
        name: "{{ docker.network }}"
