services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        restart: unless-stopped
        command: postgres -c config_file=/postgresql.conf
        user: "1000:1000"
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - POSTGRES_USER={{ postgres.username }}
            - POSTGRES_PASSWORD={{ postgres.userpass }}
            - PGDATA=/pg_data
        expose:
            - 5432
        volumes:
            # Backup path
            -  /data/postgres:/data

            # Mounted volumes
            - ./pg_data:/pg_data
            - ./logs:/logs

            # Configs and scripts
            - ./configs/postgr.sh:/postgr.sh
            - ./configs/pg_hba.conf:/pg_hba.conf
            - ./configs/postgresql.conf:/postgresql.conf

networks:
    default:
        external: true
        name: "{{ docker.network }}"
