## USAGE:
## ansible-playbook main.yml
---

-   hosts: all
    name: Main playbook

    vars_files:
        - vault.yml
        - variables.yml

    pre_tasks:
        -   name: Ensure packages
            import_tasks: tasks/packages.yml
            tags: ["packages", "update"]

    tasks:
        -   name: Host information
            debug:
                msg: |
                    host: {{ inventory_hostname }} ip: {{ ansible_host }}
                    groups: {{ group_names }} os: {{ ansible_os_family }}

        -   name: Check Ansible User
            import_tasks: tasks/useracc.yml
            tags: ["setup"]

        -   name: Check firewall rules
            import_tasks: tasks/firewall.yml
            tags: ["network"]
        
        -   name: Check hdds mounted 
            import_tasks: tasks/mount.yml
            tags: ["boot"]

        -   name: Check local hosts
            import_tasks: tasks/etc_hosts.yml
            tags: ["network"]

        -   name: Check docker
            import_tasks: tasks/docker_install.yml
            tags: ["setup"]

        # order matters!
        -   import_tasks: docker/postgres/main.yml
        -   import_tasks: docker/authelia/main.yml
        -   import_tasks: docker/nginx-proxy/main.yml

        # order does not matter
        -   import_tasks: docker/ddclient/main.yml
        -   import_tasks: docker/homepage/main.yml
        -   import_tasks: docker/adguard/main.yml
        -   import_tasks: docker/monitoring/main.yml
        -   import_tasks: docker/portainer/main.yml
        -   import_tasks: docker/pyload/main.yml
        -   import_tasks: docker/nextcloud/main.yml
        -   import_tasks: docker/kopia/main.yml
        # -   import_tasks: docker/vaultwarden/main.yml
        -   import_tasks: docker/dozzle/main.yml
