## USAGE:
## ansible-playbook main.yml
---

-   hosts: all
    name: Main playbook

    vars_files:
        - variables.yml

    pre_tasks:
        -   name: Sanity checks
            import_tasks: tasks/sanity.yml
            tags: ["always", "sanity"]

        -   name: Ensure packages
            import_tasks: tasks/packages.yml
            tags: ["packages", "update"]

    tasks:
        -   name: Host information
            debug:
                msg: |
                    host: {{ inventory_hostname }} ip: {{ ansible_host }}
                    groups: {{ group_names }} os: {{ ansible_os_family }}

        -   name: Check Ansible User
            import_tasks: tasks/useracc.yml
            tags: ["bash", "user"]

        -   name: Check local hosts
            import_tasks: tasks/etc_hosts.yml
            tags: ["network"]

        -   name: Check docker
            import_tasks: tasks/docker.yml
            tags: ["docker"]
            
        -   name: Check docker compose
            import_tasks: tasks/docker.compose.yml
            tags: ["docker"]

        -   name: Check firewall rules
            import_tasks: tasks/firewall.yml
            tags: ["firewall"]
        