---
- hosts: all
  name: Setup Server

  vars_files:
    - config.yml

  tasks:
    - name: Host information
      debug:
        msg: |
          host: {{ inventory_hostname }} ip: {{ ansible_host }}
          groups: {{ group_names }} os: {{ ansible_os_family }}

    # Setup ssh
    - import_tasks: tasks/sshd.yml

    # Install OS specific packages
    - import_tasks: tasks/packages.yml

    # Install docker
    - import_tasks: tasks/docker.yml

    # Setup fail2ban
    - import_tasks: tasks/fail2ban.yml

    # Common tasks
    - import_tasks: tasks/common.yml

    # Setup sendmail smtp host and port
    - import_tasks: tasks/sendmail.yml
