server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: system
      static_configs:
          - targets:
                - localhost
            labels:
                job: varlogs
                __path__: /var/log/*log

    - job_name: nginx
      static_configs:
          - targets:
                - localhost
            labels:
                app: nginx
                job: nginx
                __path__: /nginx/*json
                host: nginx
    #   pipeline_stages:
    #     - match:
    #         selector: '{app="nginx"}'
    #         stages:
    #         - regex:
    #             # [18/Nov/2022:23:29:56 +0000] - - 200 - GET http nginx "/stub_status" [Client 172.19.0.11] [Length 104] [Gzip -] [Sent-to ] "NGINX-Prometheus-Exporter/v0.11.0" "-"
    #             expression: '^\[(?P<timestamp>.*)\] - - (?P<code>[\d]+) - (?P<method>[^ ]*) (?P<protocol>[^ ]*) (?P<host>[^ ]*) "(?P<path>[^ ]*)" \[Client (?P<client>[^ ]*)\] (?P<rest>.*)?'
    #         - labels:
    #             timestamp:
    #             code:
    #             method:
    #             protocol:
    #             host:
    #             client:
    #             rest:

    - job_name: authelia
      static_configs:
          - targets:
                - localhost
            labels:
                app: authelia
                __path__: /authelia.log

    # - job_name: journal
    #   journal:
    #       max_age: 12h
    #       json: false
    #       labels:
    #           job: journal
    #   relabel_configs:
    #       - source_labels: [__journal__systemd_unit]
    #         target_label: systemd_unit
    #       - source_labels: [__journal__hostname]
    #         target_label: nodename
    #       - source_labels: [__journal_syslog_identifier]
    #         target_label: syslog_identifier
    #       - source_labels: [__journal__comm]
    #         target_label: command
