# Ban IPs using fail2ban
---
- tags: fail2ban
  block:
    - name: Fail2Ban config
      become: true
      template:
        src: files/system/fail2ban.j2
        dest: "/etc/fail2ban/jail.local"
        owner: root
        group: root
        mode: 0440

    - name: Fail2Ban service
      ansible.builtin.service:
        name: fail2ban
        state: enabled

    - name: Fail2Ban service
      ansible.builtin.service:
        name: fail2ban
        state: restarted

## Check status
# fail2ban-client status sshd

## Manually ban/unban ip addresses
# fail2ban-client set sshd banip IPADDRESS
# fail2ban-client set sshd unbanip IPADDRESS
