# Allow/deny ports via firewalld or ufw
---
- name: FirewallD rules
  tags: firewall
  when: ansible_os_family == "RedHat"
  block:
    - name: Add ansible port first
      become: true
      shell: "firewall-offline-cmd -p {{ansible_port}}:tcp"
      changed_when: false

    - name: FirewallD is started
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Enable rejected connection logging
      become: true
      shell: firewall-cmd --set-log-denied=all
      changed_when: false

    - name: Enable accepted connection logging
      become: true
      ansible.posix.firewalld:
        rich_rule: rule family="ipv4" source address=0.0.0.0 invert="true" log accept
        permanent: yes
        state: enabled

    -   name: Open firewalld ports
        become: true
        ansible.posix.firewalld:
            permanent: yes
            immediate: yes
            port: "{{item.port}}/{{item.proto}}"
            state: enabled
            zone: "{{item.zone}}"
        with_items: "{{ firewall.open }}"

    -   name: Block firewalld ports
        become: true
        ansible.posix.firewalld:
            permanent: yes
            immediate: yes
            port: "{{item.port}}/{{item.proto}}"
            state: disabled
            zone: "{{item.zone}}"
        with_items: "{{ firewall.block }}"

# Logging with firewalld
# sudo firewall-cmd --set-log-denied all
# firewall-cmd --add-rich-rule='rule family="ipv4" source address=0.0.0.0 invert="true" log accept'
# firewall-cmd --add-rich-rule='rule family=ipv4 source address=10.20.0.0/16 port port=1234 protocol=tcp log prefix="MyTagHere " level=info accept'
