# Allow/deny ports via firewalld or ufw
---
-   name: FirewallD rules
    when: ansible_os_family == "RedHat"
    block:
        -   name: Enable rejected connection logging
            become: true
            shell: firewall-cmd --set-log-denied=all
            changed_when: false

        -   name: Enable accepted connection logging
            become: true
            ansible.posix.firewalld:
                rich_rule: rule family="ipv4" source address=0.0.0.0 invert="true" log accept
                permanent: yes
                state: enabled

        -   name: Open firewalld ports
            become: true
            ansible.posix.firewalld:
                permanent: yes 
                immediate: yes 
                port: "{{item.port}}/{{item.proto}}"
                state: "{{item.state}}"
                zone: "{{item.zone}}"
            with_items:
                # Note: do not add ports other than the basic ones.
                # Run a reverse proxy server to give access to more ports.
                - { port: "80", proto: "tcp", state: "enabled", zone: "public" }
                - { port: "81", proto: "tcp", state: "enabled", zone: "public" }
                - { port: "443", proto: "tcp", state: "enabled", zone: "public" }
                # DNS server
                - { port: "53", proto: "tcp", state: "enabled", zone: "public" }
                - { port: "53", proto: "udp", state: "enabled", zone: "public" }


# Logging with firewalld
# sudo firewall-cmd --set-log-denied all
# firewall-cmd --add-rich-rule='rule family="ipv4" source address=0.0.0.0 invert="true" log accept'
# firewall-cmd --add-rich-rule='rule family=ipv4 source address=10.20.0.0/16 port port=1234 protocol=tcp log prefix="MyTagHere " level=info accept'
