---
- when: ansible_os_family == 'RedHat'
  tags: firewall
  block:
      - name: Enable save on stop for iptables
        become: true
        lineinfile:
            path: /etc/sysconfig/iptables-config
            regexp: "^(.*)IPTABLES_SAVE_ON_STOP(.*)$"
            line: 'IPTABLES_SAVE_ON_STOP="yes"'
            backrefs: true

      - name: Enable save on restart for iptables
        become: true
        lineinfile:
            path: /etc/sysconfig/iptables-config
            regexp: "^(.*)IPTABLES_SAVE_ON_RESTART(.*)$"
            line: 'IPTABLES_SAVE_ON_RESTART="yes"'
            backrefs: true

- name: iptables - docker logging
  tags: firewall
  block:
      - name: docker installed?
        shell: docker --version
        register: cmd_result
        failed_when: "cmd_result.rc != 0"
        changed_when: false

      - set_fact:
            ipt_dockerlog: false
            ipt_dockerchain: false

      - name: iptables - docker chain
        become: true
        shell: iptables -L DOCKER
        register: ipt
        changed_when: false

      - name: iptables - get docker chain
        set_fact:
            ipt_dockerchain: true
        when: "ipt.rc == 0"

      - name: iptables - get docker log
        set_fact:
            ipt_dockerlog: true
        when: "'IP-ACCEPT' in ipt.stdout"

      - name: iptables - docker chain logging - set
        become: true
        shell: iptables -I DOCKER 3 -i wlo1 -m limit --limit 2/second -j LOG --log-prefix="IP-ACCEPT " --log-level 4
        when: "ipt_dockerlog == false and ipt_dockerchain"

      - name: iptables - docker chain logging - update
        become: true
        shell: iptables -R DOCKER 3 -i wlo1 -m limit --limit 2/second -j LOG --log-prefix="IP-ACCEPT " --log-level 4
        when: "ipt_dockerlog and ipt_dockerchain"
