# Check if environment is properly configured to run ansible
---
- name: Localhost env
  block:
      - set_fact:
            SecretPass: "{{ lookup('env', 'SECRETPASS') }}"

      - name: SECRETPASS exported
        debug:
            msg: "SECRETPASS: {{ SecretPass }}"
        failed_when: SecretPass == ""
