# Setup user account, group, shell enviroment
---

-   name: Ansible User
    when: "'server' in group_names"
    block:
        -   name: set sudo group 
            when: ansible_os_family == "RedHat"
            set_fact:
                sudo_group: wheel

        -   name: set sudo group 
            when: ansible_os_family == "Debian"
            set_fact:
                sudo_group: root

        -   name: ansible user in sudo group
            become: true
            user:
                name: "{{ ansible_user }}"
                groups: "{{ sudo_group }}"
                state: present
                append: yes

        -   name: sudoers file of ansible user
            become: true
            template:
                src: files/system/sudoer.j2
                dest: "/etc/sudoers.d/{{ ansible_user }}"
                owner: root
                group: root
                mode: 0440

        -   name: bashrc
            when: ansible_os_family == "Debian"
            copy:
                src: files/system/bashrc.sh
                dest: "/home/{{ ansible_user }}/.bashrc"

        -   name: bashrc
            when: ansible_os_family == "RedHat"
            copy:
                src: files/system/bashrc.sh
                dest: /etc/profile.d/bashrc.sh
