services:
    # Server to store the logs.
    loki:
        image: "grafana/loki:{{ monitoring.version }}"
        container_name: loki
        volumes:
            - ./configs/loki_config.yml:/etc/loki/local-config.yaml
        ports:
            - "{{ monitoring.loki_port }}:3100"
        expose:
            - 3100
        command: -config.file=/etc/loki/local-config.yaml

    # Visualize the logs.
    grafana:
        container_name: grafana
        hostname: grafana
        user: "0"
        image: grafana/grafana
        environment:
            - "GF_SECURITY_ADMIN_USER={{ domain.username }}"
            - "GF_SECURITY_ADMIN_PASSWORD={{ domain.userpass }}"
        volumes:
            - ./configs/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
            - ./grafana_config.ini:/etc/grafana/config.ini
            - ./grafana_data:/var/lib/grafana
        command: --config /etc/grafana/config.ini
        ports:
            - 3000:3000
        expose:
            - 3000

networks:
    default:
        external: true
        name: "{{ docker.network }}"
