---
- tags: monitoring
  include_tasks: ../container.yml
  vars:
      name: monitoring
      datadir: no
      configs: yes
      templates:
          - grafana_config.ini
      extra_dirs: []

# Promtail will run on host, not as a container
- tags: monitoring
  import_tasks: promtail.yml
