---

-   tags: ["docker", "monitor"]
    when: "'server' in group_names"
    block:
        -   set_fact:
                container_root: "{{docker_fs_directory}}/monitoring"

        -   name: monitoring - dir
            file:
                path: "{{ container_root }}/"
                state: directory

        -   name: monitoring - configs
            copy:
                src: "config/"
                dest: "{{ container_root }}/config/"

        -   name: monitoring - docker compose
            template:
                src: docker-compose.j2
                dest: "{{ container_root }}/docker-compose.yml"

        -   name: monitoring - run
            become: true
            docker_compose:
                project_src: "{{ container_root }}/"
                state: present
