# Run promtail on the host to gather logs
---

- name: Install Promtail from URL
  become: true
  ansible.builtin.dnf:
    name: "https://github.com/grafana/loki/releases/download/v{{ monitoring.version }}/promtail-{{ monitoring.version }}.x86_64.rpm"
    state: present
    disable_gpg_check: true

- name: Promtail config
  become: true
  ansible.builtin.template:
    src: "promtail_config.yml"
    dest: "/etc/promtail/config.yml"
    owner: "promtail"
    group: "promtail"
    mode: "0644"
    validate: "/usr/bin/promtail -check-syntax -config.file %s"

- name: Add the Promtail system user to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "promtail"
    groups: "systemd-journal"
    system: true
    append: true
    create_home: false
    state: present


- name: restart promtail service
  block:
    - become: true
      service:
        name: promtail
        state: restarted
        enabled: true
  rescue:
    - name: Promtail service error
      debug:
        msg: |
          Failed to restart promtail service.
          Please restart manually.


- name: Verify that Promtail URL is responding
  ansible.builtin.uri:
    url: "http://{{ monitoring.promtail_listen }}:{{ monitoring.promtail_port }}/ready"
    method: GET
  register: promtail_verify_url_status_code
  retries: 3
  delay: 5
  until: promtail_verify_url_status_code.status == 200
