services:
    nginx-proxy:
        image: "jc21/nginx-proxy-manager:latest"
        container_name: nginx-proxy
        restart: unless-stopped
        user: "root"        # must be run as root
        environment:
            - TZ='America/New_York'
            - USER_UID=1000
            - USER_GID=1000
            - PUID=1000
            - PGID=1000
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            # Mounted volumes
            - ./data/:/data:shared
            - ./letsencrypt:/etc/letsencrypt

            # Configs and scripts
            - ./configs:/snippets

networks:
    default:
        external: true
        name: "{{ docker.network }}"

## SSL Certificate for wildcard domain
# docker exec -it nginx-proxy_app_1 bash
# certbot -d *.example.com --manual --preferred-challenges dns certonly
# Deploy a DNS TXT record under the name _acme-challenge.example.com with:
# In your google domain administration, add a custom record.
# Change the record to a TXT record.
# Ensure the sub domain is _acme-challenge
# Copy and paste the generated value from your certbot window as the value for your txt record.
# Once this is done, cross-check following the url, Press ENTER to continue.
# The crertificates will be saved in ./letsencrypt/archive/example.com/
# Copy the files to your localhost using rsync and upload to npm web ui.
# -------------
