---

-   tags: ["docker", "homepage"]
    when: "'server' in group_names"
    block:
        -   set_fact:
                container_root: "{{docker_fs_directory}}/homepage"

        -   name: homepage - config dir
            file:
                path: "{{ container_root }}/config/"
                state: directory

        -   name: homepage - static config
            copy:
                src: config/
                dest: "{{ container_root }}/config/"

        -   name: homepage - dynamic config
            template:
                src: "{{ item }}.yml.j2"
                dest: "{{ container_root }}/config/{{ item }}.yaml"
            loop:
                - settings
                - services
                - widgets

        -   name: homepage - docker compose
            template:
                src: docker-compose.j2
                dest: "{{ container_root }}/docker-compose.yml"

        -   name: homepage - run
            docker_compose:
                project_src: "{{ container_root }}/"
                state: present
