---

-   tags: telegram
    when: "'telegram' in docker_containers"
    block:
        -   name: Telegram
            file:
                path: "{{docker_fs_directory}}/telegram/"
                state: directory

        -   name: Telegram - docker compose
            template:
                src: "docker-compose.j2"
                dest: "{{docker_fs_directory}}/telegram/docker-compose.yml"

        -   name: Telegram - run
            community.docker.docker_compose_v2:
                project_src: "{{docker_fs_directory}}/telegram/"
                remove_orphans: yes
                state: present
            register: output

        - debug:
            var: output

-   when: "'telegram' in remove_containers"
    stat:
        path: "{{docker_fs_directory}}/telegram/"
    register: cdir

-   tags: telegram
    when:
        - "'telegram' in stop_containers"
        - cdir.stat.isdir is defined and cdir.stat.isdir
    block:
        -   name: Telegram - stop
            community.docker.docker_compose_v2:
                project_src: "{{docker_fs_directory}}/telegram/"
                state: stopped

-   tags: telegram
    when:
        - "'telegram' in remove_containers"
        - cdir.stat.isdir is defined and cdir.stat.isdir
    block:
        -   name: Telegram - stop
            community.docker.docker_compose_v2:
                project_src: "{{docker_fs_directory}}/telegram/"
                state: absent
            register: output

        -   name: Telegram - remove
            community.docker.docker_compose_v2:
                project_src: "{{docker_fs_directory}}/telegram/"
                remove_volumes: yes
                remove_images: all
                state: absent
            register: output

        -   debug:
                var: output

        -   name: Telegram - remove docker compose
            file:
                path: "{{docker_fs_directory}}/telegram/docker-compose.yml"
                state: absent

        -   name: Telegram - remove container directory
            file:
                path: "{{docker_fs_directory}}/telegram/"
                state: absent
