---

-   tags: ["docker", "autosel"]
    when: "'server' in group_names"
    block:
        -   set_fact:
                container_root: "{{docker_fs_directory}}/autosel"

        -   name: autosel - dirs
            file:
                path: "{{ container_root }}/{{ item }}"
                state: directory
            loop:
                - data 

        -   name: autosel - docker compose
            template:
                src: docker-compose.j2
                dest: "{{ container_root }}/docker-compose.yml"

        -   name: autosel - run
            docker_compose:
                project_src: "{{ container_root }}/"
                state: present
